dronedodgeball-ppo-lstm:
    env: DroneDodgeBall-v0
    run: PPO
    stop:
        episode_reward_mean: 99999 # use time steps as stopping criteria
        timesteps_total: 8000000
    config:
        num_workers: 1
        framework: tf
        # environment
        env_config:
          use_ball_pose: true
          use_held_ball: true
          input_mode: 1
        # sgd-related
        lr: 0.0002
        lr_schedule: [[0, 0.0002], [8000000, 0.0]]
        num_sgd_iter: 8
        train_batch_size: 10240
        sgd_minibatch_size: 512
        # MDP-related
        gamma: 0.99
        rollout_fragment_length: 64
        # value function
        vf_share_layers: true
        vf_loss_coeff: 1.0
        # PPO-specific
        entropy_coeff: 0.01
        lambda: 0.95
        kl_target: 0.2
        # model
        model:
          fcnet_hiddens: [16, 32, 32]
          fcnet_activation: swish
          use_lstm: true
          lstm_cell_size: 32
          lstm_use_prev_action_reward: true
          max_seq_len: 32